feat(config): make wallet application and paths configurable
eclipse-tractusx/ssi-credential-issuer pull request #230
Opened 2024-08-02 09:19 UTC by Phil91

## Description

* make application of the wallet configurable
* make wallet paths configurable

## Why

To be able to support multiple wallets

## Issue

Refs: #226

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/ssi-credential-issuer/blob/main/docs/technical-documentation/dev-process/How%20to%20contribute.md)
- [x] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [x] I have created and linked IP issues or requested their creation by a committer
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added copyright and license headers, footers (for .md files) or files (for images)

2024-08-13 17:58 UTC, evegufy requested changes

2024-08-14 08:22 UTC, Phil91 commented on src/externalservices/Wallet.Service/DependencyInjection/WalletSettings.cs
> +    public string CredentialCreationPath { get; set; } = null!;
adjusted

2024-08-14 08:22 UTC, Phil91 commented on src/externalservices/Wallet.Service/DependencyInjection/WalletSettings.cs
> +    public string SigningCredentialPath { get; set; } = null!;
adjusted

2024-08-14 08:22 UTC, Phil91 commented on charts/ssi-credential-issuer/values.yaml
> +    getCreationPath: "/api/v2.0.0/credentials/{0}"
adjusted

2024-08-14 08:23 UTC, Phil91 commented on charts/ssi-credential-issuer/values.yaml
> +    # -- path to revoke a specific credential {0} will be replaced by the credential id
adjusted

2024-08-14 08:23 UTC, Phil91 commented on charts/ssi-credential-issuer/values.yaml
> +    # -- path to get a specific credential {0} will be replaced by the credential id
adjusted

2024-08-14 08:23 UTC, Phil91 commented on charts/ssi-credential-issuer/values.yaml
> +    # -- path to sign a specific credential {0} will be replaced by the credential id
adjusted

2024-08-14 08:23 UTC, Phil91 commented on charts/ssi-credential-issuer/values.yaml
> +    signingCreationPath: "/api/v2.0.0/credentials/{0}"
adjusted

2024-08-14 15:08 UTC, evegufy requested changes

2024-08-14 15:08 UTC, evegufy commented on src/processes/Processes.Worker/appsettings.json
> +    "SigningCredentialPath": "",
```suggestion
    "SignCredentialPath": "",
```

2024-08-14 18:03 UTC, merged