feat(notification): adjust notification request parameter
eclipse-tractusx/ssi-credential-issuer pull request #233
Opened 2024-08-08 11:42 UTC by Phil91

## Description

Adjust the request parameter to create notifications

## Why

The portal backend changed the request structure to create notifications

## Issue

Refs: https://github.com/eclipse-tractusx/portal-backend/issues/812

## Corresponding Backend PR 

## Corresponding Iam PR

https://github.com/eclipse-tractusx/portal-iam/pull/169

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/ssi-credential-issuer/blob/main/docs/technical-documentation/dev-process/How%20to%20contribute.md)
- [x] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [x] I have created and linked IP issues or requested their creation by a committer
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added copyright and license headers, footers (for .md files) or files (for images)

2024-08-14 08:20 UTC, ntruchsess requested changes

2024-08-14 08:27 UTC, Phil91 commented on tests/externalservices/Portal.Service.Tests/PortalServiceTests.cs
> +            ((x.Content as JsonContent)!.Value as NotificationRequest)!.Receiver == requester &&
adjusted

2024-09-19 13:12 UTC, evegufy approved these changes

2024-09-23 10:44 UTC, ntruchsess approved these changes

2024-09-23 11:05 UTC, merged