Feature/209 retrigger
eclipse-tractusx/ssi-credential-issuer pull request #242
Opened 2024-08-23 10:24 UTC by Phil91

## Description

* add retrigger logic for processes
* add documentation for processes

## Why

To give the possibility to retrigger processes that failed

## Issue

Refs: #209 

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/ssi-credential-issuer/blob/main/docs/technical-documentation/dev-process/How%20to%20contribute.md)
- [x] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [x] I have created and linked IP issues or requested their creation by a committer
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added copyright and license headers, footers (for .md files) or files (for images)

2024-08-23 10:27 UTC, Phil91 commented
@evegufy @ntruchsess this Pr should be merged after #235 is merged

2024-09-24 13:43 UTC, evegufy requested changes

2024-09-24 13:43 UTC, evegufy commented on docs/technical-documentation/processes/01. create_credential.md
I think it would make sense to locate the new documentation already under `docs/admin/processes`

2024-09-24 13:43 UTC, evegufy commented on src/database/SsiCredentialIssuer.Entities/Extensions/ProcessStepTypeExtensions.cs
Please add file header

2024-09-24 14:24 UTC, evegufy approved these changes

2024-09-24 16:04 UTC, merged