feat: make statuslist type configureable
eclipse-tractusx/ssi-credential-issuer pull request #298
Opened 2024-11-12 14:31 UTC by Phil91

## Description

The statuslist type used for the credentials is now configureable

## Why

Since the currently used type for the status list (Statuslist2021) was hardcoded the type used in the credentials for the status list is now configureable to be able to use the BitstringStatusList

## Issue

Refs: #224

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/ssi-credential-issuer/blob/main/docs/technical-documentation/dev-process/How%20to%20contribute.md)
- [x] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [x] I have created and linked IP issues or requested their creation by a committer
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added copyright and license headers, footers (for .md files) or files (for images)

2024-11-12 15:15 UTC, evegufy requested changes
helm install fails, could you please check?

As https://github.com/eclipse-tractusx/ssi-credential-issuer/issues/224 contains a lot of different information, could you please create an own issue for that, similar to this one https://github.com/eclipse-tractusx/ssi-credential-issuer/issues/226?

2024-12-03 07:51 UTC, MaximilianHauer commented
@evegufy  how do we proceed based on the last SSI EG meeting ?

2025-02-05 14:41 UTC, evegufy approved these changes

2025-02-05 14:43 UTC, evegufy commented
> @evegufy how do we proceed based on the last SSI EG meeting ?

we still go ahead with the change, as it just enable configurability and the config default to statuslist2021

2025-02-05 14:43 UTC, merged